application: wxturbidsoul
version: 1
runtime: python27
api_version: 1
threadsafe: yes


builtins:
- appstats: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: /task/.*
  script: task.app
  login: admin

- url: .*
  script: wx.app

libraries:
- name: webapp2
  version: "2.5.1"
